
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Maioanh.1
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: DoAn_development

test:
  <<: *default
  database: DoAn_test

production:
  <<: *default
  database: DoAn_production
  username: DoAn
  password: <%= ENV['DOAN_DATABASE_PASSWORD'] %>
